version: '3'

services:
  mongo:
    image: "bitnami/mongodb:3.6.19-debian-9-r25"
    container_name: "${PROJECT_ALIAS}_MONGO"
    ports: 
      - 27017:${MONGO_PORT}

  api:
    environment:
      PROJECT_ALIAS:
    container_name: "${PROJECT_ALIAS}_API"
    build: 
      context: ./api
      args:
        API_SECRET:
        API_URL:
        API_INT_PORT:
        MONGO_URI:
        WEB_SECRET:  
    volumes:
      - ./api/src:/node-app/src
      - ./api/__tests__:/node-app/__tests__
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - ${API_INT_PORT}:${API_EXT_PORT}

  web:
    container_name: "${PROJECT_ALIAS}_WEB"
    build: 
      context: ./web
      args:
        API_URL:
        WEB_INT_PORT:
        WEB_SECRET:
    volumes:
      - ./web/src:/node-app/src
      - ./web/public:/node-app/public
      - ./web/test:/node-app/test
    depends_on:
      - api
      - mongo
    links:
      - api
    ports:
      - ${WEB_INT_PORT}:${WEB_EXT_PORT}







      